### PR TITLE
Reformatted the Breakfast Recipe

### PR DESCRIPTION
**Pull request by gdempse**
Added some formatting

## 🎯 Objective

Revisiting the Breakfast Recipe Because we closed it before everyone made a commit on the branch

## 🛠️ Changes made

Formatting

## 👥 Who needs to review this Pull Request? 

@gdempse @cakpati @nohanoweir @lbisinoto 
_Pull Requests should include commits from each member of your group._

### CODE REVIEW

**Comment by lbisinoto** [comment]
I'll wait for someone else to approve this recipe before committing to main branch, ok team? I believe that @nohanoweir and @cakpati are the ones who need to take action now..

**Review by cakpati — APPROVED** [review]
Changes look good to me!

**Review by lbisinoto — APPROVED** [review]
looks good for me!! can I merge this or does anyone else need to approve?

**Comment by nohanoweir** [comment]
I wasn't on the reviewer list. I can merge it!

**Pull request merged**
