### PR TITLE
Update breakfast readme

### PR DESCRIPTION
**Pull request by colton1493**
Added line under notes

## 🎯 Objective

Give more detail under notes

## 🛠️ Changes made

Added line "best enjoyed with a friend"

## 👥 Who needs to review this Pull Request? 

@lbisinoto @gdempse @nohanoweir @cakpati

### CODE REVIEW

**Comment by colton1493** [comment]
Hey @lbisinoto @gdempse @cakpati @nohanoweir let me know what you think of these changes, thanks!

**Review by lbisinoto — APPROVED** [review]
agreed!

**Review by gdempse — APPROVED** [review]
Nice touch

**Review by lbisinoto — APPROVED** [review]
the more the merrier

**Review by nohanoweir — COMMENTED** [review]
Love it!

**Review by nohanoweir — APPROVED** [review]

**Pull request merged**
